//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int id_telefono { get; set; }
        public string marca { get; set; }
        public double precio { get; set; }
        public int id_gama { get; set; }
        public int id_ensamble { get; set; }
        public int id_color { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Ensamble Ensamble { get; set; }
        public virtual Gama Gama { get; set; }
    }
}
